type SwapTransaction @entity {
  id: ID!
  sender: String!
  tokenIn: String!
  tokenOut: String!
  amountIn: BigDecimal!
  amountOut: BigDecimal!
  chain: String!
  status: String!
  blockTimestamp: BigInt!
}

type BridgeTransaction @entity {
  id: ID!
  sender: String!
  sourceChain: String!
  destinationChain: String!
  amount: BigDecimal!
  status: String!
  blockTimestamp: BigInt!
}

type GlobalStat @entity {
  id: ID!
  totalValueProcessedUSD: BigDecimal!
  totalTransactions: BigInt!
  activeUsersCount: BigInt!
}
